config/routes.rb
Rails.application.routes.draw do

  get 'customers/orders/thanx' => 'customer/orders#thanx',as: 'thanx'

  devise_scope :customer do
    get '/customers/sign_out' => 'devise/sessions#destroy'
    get '/customers/log_in' => 'devise/sessions#customer/devise/sessions/new'
    get '/customer/cart_items/:id' => 'customer/cart_items#destroy'
    get '/customer/shipping_addresses/:id' => 'customer/shipping_addresses#destroy'
  end

  devise_scope :admin do
    get '/admins/sign_out' => 'admin/sessions#destroy',as: 'admin_sign_out'
    get '/admins/sign_in' => 'admin/sessions#new',as: 'admin_sign_in'
  end

  devise_for :customers, controllers: {
        sessions: 'customer/sessions',
        registrations: 'customer/registrations'
      }

  devise_for :admins, controllers: {
        sessions: 'admin/sessions'
      }

  root to: 'homes#top'
  get 'customers/:id/exit' => 'customer/customers#exit',as: 'customer_exit'
  get 'customers/:id/withdrawal' => 'customer/customers#withdrawal', as: 'withdrawal'
  get 'customers/orders/confirm' => 'customer/orders#confirm',as: 'confirm'
  namespace :customer do
    resources :customers,only: [:show,:edit,:update,:destroy]
    resources :cart_items,only:[:index,:create,:destroy,:update]
    resources :items,only:[:index,:edit,:show,:create]
    resources :shipping_addresses,only:[:index,:create,:edit,:destroy,:update]
    resources :orders,only:[:index,:show,:new,:create]
    # CartItem
    get 'cart_item/destroy_all' => 'cart_items#destroy_all'
  end


  get 'homes/about'


  namespace :admin do
    root to: "homes#top"
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :ordered_items, only: [:update]
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items, through: :cart_items
  has_many :cart_items, dependent: :destroy
  has_many :orders
  has_many :shipping_addresses

  def full_name
    self.last_name + " " + self.first_name
  end

  def full_name_kana
    self.last_name_kana + " " + self.first_name_kana
  end

  def active_for_authentication
    super && (is_deleted == false)
  end

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true, uniqueness: true,length: {minimum: 9}

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :items, through: :ordered_items
  has_many :ordered_items
  enum payment_method: { クレジットカード: 0 ,銀行振込: 1 }
  enum status:{入金待ち: 0 ,入金確認: 1,製作中: 2,発送準備中: 3,発送済み: 4}

  validates  :customer_id, presence: true
  validates  :name,presence: true
  validates  :postal_code,presence: true
  validates  :address,presence: true

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    render action: :show
  end

  private
   def customer_params
     params.require(:customer).permit(:first_name,:last_name,:first_name_kana,:last_name_kana,:email,:postal_code,:address,:telphone_number,:is_deleted)
   end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!



  def index
  	@orders = Order.page(params[:page]).per(7)
  end

  def show
  	@order = Order.find(params[:id])
  	@ordered_items = @order.ordered_items
  end

  def update
    @order = Order.find(params[:id])
    @order.update(orders_params)
    @ordered_items = @order.ordered_items.all

    if @order.status == "入金確認"
	     @ordered_items.update_all(making_status: "製作待ち")
    end
       redirect_to admin_order_path(@order.id)
  end




  private

  def orders_params
    params.require(:order).permit(:status)
  end
end

app/controllers/customer/cart_items_controller.rb
class Customer::CartItemsController < ApplicationController

  def index
    @cart_items = CartItem.where(customer_id: current_customer.id)
    @cart_item = CartItem.new
    # @total = @cart_items.inject(0) { |sum, item| sum + item.tax_out_price }
  end

  def create
   @cart_item = current_customer.cart_items.new(params_cart_item)
   @cart_item.volume += params[:volume].to_i
   @cart_item.save
   redirect_to customer_cart_items_path

  end

  def update
    @cart_item = CartItem.find(params[:id])
    @cart_item.update(params_cart_item)
    redirect_to customer_cart_items_path
  end

  def destroy
    @cart_item= CartItem.find(params[:id])
    @cart_item.destroy
    redirect_to customer_cart_items_path
  end

  def destroy_all
    @cart_items = current_customer.cart_items
    @cart_items.destroy_all
    redirect_to customer_cart_items_path
  end

  private

  def params_cart_item
    params.require(:cart_item).permit(:volume, :item_id, :customer_id)
  end


end

app/controllers/customer/confirmations_controller.rb
# frozen_string_literal: true

class Customer::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController
  def show
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to customer_customer_path(@customer.id)
  end

  def exit

  end

  def withdrawal
    @customer = Customer.find(params[:id])
    @customer.update(is_deleted: true)
    reset_session
    flash[:notice] = "退会処理を実行いたしました"
    redirect_to root_path
  end


  private

  def customer_params
    params.require(:customer).permit(:last_name,:first_name,:last_name_kana,:first_name_kana,:postal_code,:address,:telephone_number)
  end
end

app/controllers/customer/items_controller.rb
class Customer::ItemsController < ApplicationController

  def index
    @items = Item.page(params[:page]).reverse_order
  end

  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
  end


  private

  def cart_item_params
    params.require(:cart_item).permit(:volume)
  end
end

app/controllers/customer/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customer::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
  def index
    @orders = current_customer.orders
  end

  def show
    @order = Order.find(params[:id])
    @ordered_items = @order.ordered_items
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    @order.customer_id = current_customer.id
    @order.shipping_cost = 800
    @order.save!
    @cart_items = current_customer.cart_items
  @cart_items.each do |cart_item|
    @ordered_item = OrderedItem.new
    @ordered_item.order_id = @order.id
    @ordered_item.item_id = cart_item.item.id
    @ordered_item.making_status = 0
    @ordered_item.tax_in_price = cart_item.item.tax_out_price * 1.1.floor
    @ordered_item.volume = cart_item.volume
    @ordered_item.save
    cart_item.destroy
  end
    redirect_to thanx_path
  end

  def confirm
    @order = Order.new
    @order.payment_method = params[:order][:payment_method].to_i
    @order.address_option = params[:order][:address_option].to_i
    @order.status = params[:order][:status].to_i
    @order.shipping_cost = 800
    @cart_items = CartItem.where(customer_id: current_customer.id )


  if params[:order][:address_option] == "0"
     @order.address = current_customer.address
     @order.postal_code = current_customer.postal_code
     @order.customer_id = current_customer.id
     @order.name = current_customer.last_name + current_customer.first_name

  elsif
    params[:order][:address_option] == "1"
    @sta = params[:order][:address_id].to_i
    @order_address = ShippingAddress.find(@sta)
    @order.postal_code = @order_address.postal_code
    @order.address = @order_address.address
    @order.name = @order_address.name
  else
    @order.postal_code = params[:order][:postal_code]
    @order.address = params[:order][:address]
    @order.name = params[:order][:name]
  end


  end

  def thanx

  end

  private

  def order_params
    params.require(:order).permit(:name,:address,:postal_code,:billing_amount,:payment_method,:status,:address_option)
  end

end

app/controllers/customer/passwords_controller.rb
# frozen_string_literal: true

class Customer::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customer/registrations_controller.rb
# frozen_string_literal: true

class Customer::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

   #The path used after sign up for inactive accounts.
   def after_sign_up_path_for(resource)
    customer_customer_path(current_customer.id)
   end
end

app/controllers/customer/sessions_controller.rb
# frozen_string_literal: true

class Customer::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customer/shipping_addresses_controller.rb
class Customer::ShippingAddressesController < ApplicationController

  def index
    @shipping_addresses = current_customer.shipping_addresses
    @shipping_address = ShippingAddress.new
  end

  def create
    @shipping_address = ShippingAddress.new(shipping_address_params)
    @shipping_address.customer_id = current_customer.id
    @shipping_address.save
    redirect_to customer_shipping_addresses_path
  end

  def edit
    @shipping_address = ShippingAddress.find(params[:id])
  end

  def update
    @shipping_address = ShippingAddress.find(params[:id])
    @shipping_address.update(shipping_address_params)
    redirect_to customer_shipping_addresses_path
  end

  def destroy
    @shipping_address = ShippingAddress.find(params[:id])
    @shipping_address.destroy
    redirect_to customer_shipping_addresses_path
  end



  private

  def shipping_address_params
   params.require(:shipping_address).permit(:postal_code, :address, :name)
  end

end

app/controllers/customer/unlocks_controller.rb
# frozen_string_literal: true

class Customer::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/customer/orders_helper.rb
module Customer::OrdersHelper
end

app/helpers/customer/shipping_addresses_helper.rb
module Customer::ShippingAddressesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customer/orders/confirm.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-7 mt-5 pt-3">
        <h5 class="mb-4 h4">注文情報確認</h5>
        <table class="table">
          <thead class="thead-light">
            <tr>
              <th scope="col">商品名</th>
              <th scope="col">単価（税込）</th>
              <th scope="col">数量</th>
              <th scope="col">小計</th>
            </tr>
          </thead>
           <% total_price = 0 %>
           <% @cart_items.each do |cart_item| %>

           <% tax_in_price = cart_item.item.tax_out_price * 1.1 %>
          <tbody>
            <tr>
              <td><%= cart_item.item.name %></td>
              <td><%= tax_in_price.floor %>円</td>
              <td><%= cart_item.volume %>個</td>
              <td><%= tax_in_price.floor * cart_item.volume %>円</td>
            </tr>
            <% sum = tax_in_price.floor * cart_item.volume %>
            <% total_price += sum %>
          </tbody>
          <% end %>
        </table>
        <h5 class="mt-5 h4">支払い方法</h5>
        <p class="mt-4 ml-5">
          <%= @order.payment_method %>
        </p>
        <h5 class="mt-5 h4">お届け先</h5>
        <p class="mt-4 ml-5">
          <%= @order.postal_code %> <%= @order.address %>
        </p>
      </div>
      <div class="col-4 mt-5 pt-5">
        <table class="table">

          <tr>
            <th>送料</th><td>800円</td>
          </tr>

          <tr>
            <th>商品合計</th><td><%= total_price %>円</td>
          </tr>

          <tr>
            <th>請求金額</th><td><%= total_price + 800 %>円</td>
          </tr>
        </table>
      </div>
    </div>
  </div>
  <div class="text-center mt-5">
    <%= form_with model: @order, url: customer_orders_path, method: :post ,local:true do |f| %>
    <%= f.hidden_field :name, :value => @order.name %>
    <%= f.hidden_field :address , :value =>  @order.address %>
    <%= f.hidden_field :postal_code, :value => @order.postal_code %>
    <%= f.hidden_field :billing_amount, :value => total_price + 800 %>
    <%= f.hidden_field :payment_method, :value => @order.payment_method %>
    <%= f.hidden_field :status, :value => @order.status %>
    <%= f.hidden_field :address_option , :value => @order.address_option %>
    <%= f.submit '注文を確定する', class: "btn btn-success" %>
    <% end %>
  </div>
</main>

app/views/customer/orders/index.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="mt-5 p-5">
        <h5 class="mb-4">注文履歴一覧</h5>
        <table class="table">
          <thead class="thead-light">
            <tr>
              <th scope="col">注文日</th>
              <th scope="col">配送先</th>
              <th scope="col">注文商品</th>
              <th scope="col">支払金額</th>
              <th scope="col">ステータス</th>
              <th scope="col">注文詳細</th>
            </tr>
          </thead>
          <% @orders.each do |order| %>
            <tbody>
              <tr>
                <td><%= order.created_at.strftime('%Y/%m/%d') %></td>
                <td>
                  〒<%= order.postal_code %><br>
                  <%= order.address %><br>
                  <%= order.name %>
                </td>
                <td>
                  <% total = 0 %>
                  <% order.ordered_items.each do |ordered_item| %>
                    <%= ordered_item.item.name %><br>

                    <% total += (ordered_item.item.tax_out_price*1.1*ordered_item.volume).floor %>

                  <% end %>
                </td>
                <td><%= total.to_s(:delimited) %>円</td>
                <td><%= order.status %></td>
                <td><%= link_to "表示する", customer_order_path(order.id) %> </td>
              </tr>
            </tbody>
          <% end %>
        </table>
    </div>
  </div>
</main>

app/views/customer/orders/new.html.erb
<main class="pl-5">
  <h5 class="ml-5 mt-4 mb-4">注文情報入力</h5>
  <%= form_with model: @order, url: "/customers/orders/confirm",method: :get,local: true do |f| %>
      <%= f.label :payment_method, "支払い方法",class: "ml-4" %>
      <br>
      <div class="payment-option ml-5">
        <%= f.radio_button :payment_method, 0,  checked: "checked" %>
        <%= f.label :payment_method, "クレジットカード" %>
      <br>
        <%= f.radio_button :payment_method,1 %>
        <%= f.label :payment_method, "銀行振込" %>
      </div>
      <%= f.label :address, "お届け先",class: "ml-4" %>
      <div class="shipping-option ml-5">
        <%= f.radio_button :address_option, 0, checked: "checked" %>
        <%= f.label :address, "ご自身の住所", class: "mb-4" %>
        <%= current_customer.postal_code %>
        <%= current_customer.address %>
        </br>
        <%= f.radio_button :address_option, 1 %>
        <%= f.label :address, "登録済住所から選択", class: "mb-4" %>
        <%= f.collection_select :address_id , current_customer.shipping_addresses, :id, :full_address, :include_blank => "選択してください" %>
        <br>
        <%= f.radio_button :address_option, 2 %>
        <%= f.label :address, "新しいお届け先", class: "mb-4" %>
        <br>
        <%= f.label :postal_code, "郵便番号(ハイフンなし）", class:"mr-3" %>
        <%= f.text_field :postal_code %>
        <br>
        <%= f.label :address, "住所", class:"mr-5" %>
        <%= f.text_field :address %>
        <br>
        <%= f.label :name, "宛名" ,class:"mr-5 mb-5" %>
        <%= f.text_field :name %>
        <br>
        <%= f.hidden_field :status, :value => 0 %>
        <%= f.submit "確認画面へ進む" , class:"btn btn-primary" %>
      </div>
  <% end %>
</main>

app/views/customer/orders/show.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-6">
        <h5 class="mt-5 mb-5">注文履歴詳細</h5>
        <p>注文情報</p>
        <table class="table">
          <tr>
            <th scope="col">注文日</th><td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
          </tr>

          <tr>
            <th scope="col">配送先</th>
            <td>
              〒<%= @order.postal_code %><br>
              <%= @order.address %><br>
              <%= @order.name %>
            </td>
          </tr>

          <tr>
            <th scope="col">支払い方法</th><td><%= @order.payment_method %></td>
          </tr>

          <tr>
            <th scope="col">ステータス</th><td><%= @order.status %></td>
          </tr>
        </table>
      </div>
      <div class="col-3 mt-5 pt-5">
          <p class="mt-4">請求情報</p>
          <table class="table">
            <tr>
              <th scope="col">商品合計</th>
              <td>
                <% total = 0 %>
                <% @ordered_items.each do |ordered_item| %>
                 <% total += (ordered_item.item.tax_out_price*1.1*ordered_item.volume).floor %>
                <% end %>
                <%= total %>円
              </td>
            </tr>

            <tr>
              <th scope="col">配送料</th><td>800円</td>
            </tr>

            <tr>
              <th scope="col">ご請求額</th><td><%= (total + 800).floor %>円</td>
            </tr>

          </table>
        </div>
    </div>

    <div class="row">
      <div class="col-8 mt-3">
          <p class="mt-4">注文内容</p>
          <table class="table">
          <thead class="thead-light">
            <tr>
              <th scope="col">商品</th>
              <th scope="col">単価（税込）</th>
              <th scope="col">個数</th>
              <th scope="col">小計</th>
            </tr>
          </thead>
          <% @ordered_items.each do |ordered_item| %>
            <tbody>
              <tr>
                <td><%= ordered_item.item.name %></td>
                <td><%= ordered_item.tax_in_price.floor %>円</td>
                <td><%= ordered_item.volume %></td>
                <td>
                 <% prise = (ordered_item.volume * ordered_item.tax_in_price).floor %>
                 <%= prise %>円
                </td>
              </tr>
            </tbody>
          <% end %>
        </table>
      </div>
    </div>

  </div>
</main>

app/views/customer/orders/thanx.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-3">

      </div>
      <div class="col-6">
        <h3 class="mt-5 pt-5">ご注文ありがとうございました！</h3>
      </div>
      <div class="col-3">

      </div>
    </div>
  </div>
</main>