config/routes.rb
Rails.application.routes.draw do

  get 'customers/orders/thanx' => 'customer/orders#thanx',as: 'thanx'

  devise_scope :customer do
    get '/customers/sign_out' => 'devise/sessions#destroy'
    get '/customers/log_in' => 'devise/sessions#customer/devise/sessions/new'
    get '/customer/cart_items/:id' => 'customer/cart_items#destroy'
    get '/customer/shipping_addresses/:id' => 'customer/shipping_addresses#destroy'
  end

  devise_scope :admin do
    get '/admins/sign_out' => 'admin/sessions#destroy',as: 'admin_sign_out'
    get '/admins/sign_in' => 'admin/sessions#new',as: 'admin_sign_in'
  end

  devise_for :customers, controllers: {
        sessions: 'customer/sessions',
        registrations: 'customer/registrations'
      }

  devise_for :admins, controllers: {
        sessions: 'admin/sessions'
      }

  root to: 'homes#top'
  get 'customers/:id/exit' => 'customer/customers#exit',as: 'customer_exit'
  get 'customers/:id/withdrawal' => 'customer/customers#withdrawal', as: 'withdrawal'
  get 'customers/orders/confirm' => 'customer/orders#confirm',as: 'confirm'
  namespace :customer do
    resources :customers,only: [:show,:edit,:update,:destroy]
    resources :cart_items,only:[:index,:create,:destroy,:update]
    resources :items,only:[:index,:edit,:show,:create]
    resources :shipping_addresses,only:[:index,:create,:edit,:destroy,:update]
    resources :orders,only:[:index,:show,:new,:create]
    # CartItem
    get 'cart_item/destroy_all' => 'cart_items#destroy_all'
  end


  get 'homes/about'


  namespace :admin do
    root to: "homes#top"
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :ordered_items, only: [:update]
  end

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :items, through: :ordered_items
  has_many :ordered_items
  enum payment_method: { クレジットカード: 0 ,銀行振込: 1 }
  enum status:{入金待ち: 0 ,入金確認: 1,製作中: 2,発送準備中: 3,発送済み: 4}

  validates  :customer_id, presence: true
  validates  :name,presence: true
  validates  :postal_code,presence: true
  validates  :address,presence: true

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!



  def index
  	@orders = Order.page(params[:page]).per(7)
  end

  def show
  	@order = Order.find(params[:id])
  	@ordered_items = @order.ordered_items
  end

  def update
    @order = Order.find(params[:id])
    @order.update(orders_params)
    @ordered_items = @order.ordered_items.all

    if @order.status == "入金確認"
	     @ordered_items.update_all(making_status: "製作待ち")
    end
       redirect_to admin_order_path(@order.id)
  end




  private

  def orders_params
    params.require(:order).permit(:status)
  end
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
  def index
    @orders = current_customer.orders
  end

  def show
    @order = Order.find(params[:id])
    @ordered_items = @order.ordered_items
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    @order.customer_id = current_customer.id
    @order.shipping_cost = 800
    @order.save!
    @cart_items = current_customer.cart_items
  @cart_items.each do |cart_item|
    @ordered_item = OrderedItem.new
    @ordered_item.order_id = @order.id
    @ordered_item.item_id = cart_item.item.id
    @ordered_item.making_status = 0
    @ordered_item.tax_in_price = cart_item.item.tax_out_price * 1.1.floor
    @ordered_item.volume = cart_item.volume
    @ordered_item.save
    cart_item.destroy
  end
    redirect_to thanx_path
  end

  def confirm
    @order = Order.new
    @order.payment_method = params[:order][:payment_method].to_i
    @order.address_option = params[:order][:address_option].to_i
    @order.status = params[:order][:status].to_i
    @order.shipping_cost = 800
    @cart_items = CartItem.where(customer_id: current_customer.id )


  if params[:order][:address_option] == "0"
     @order.address = current_customer.address
     @order.postal_code = current_customer.postal_code
     @order.customer_id = current_customer.id
     @order.name = current_customer.last_name + current_customer.first_name

  elsif
    params[:order][:address_option] == "1"
    @sta = params[:order][:address_id].to_i
    @order_address = ShippingAddress.find(@sta)
    @order.postal_code = @order_address.postal_code
    @order.address = @order_address.address
    @order.name = @order_address.name
  else
    @order.postal_code = params[:order][:postal_code]
    @order.address = params[:order][:address]
    @order.name = params[:order][:name]
  end


  end

  def thanx

  end

  private

  def order_params
    params.require(:order).permit(:name,:address,:postal_code,:billing_amount,:payment_method,:status,:address_option)
  end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/customer/orders_helper.rb
module Customer::OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class="container">
  <div class="admin-order-index pt-5">
    <h4 class="pb-3">注文履歴一覧</h4>
    <table class="table">
      <tr class="table-active">
        <th>購入日時</th>
        <th>購入者</th>
        <th>注文個数</th>
        <th>注文ステータス</th>
      </tr>
      <% @orders.each do |order| %>
        <tr>
          <td>
            <%= link_to admin_order_path(order) do %>
            <%= order.created_at. strftime('%Y/%m/%d/%R') %>
            <% end %>
          </td>
          <td>
            <%= order.customer.full_name %>
          </td>
          <td>
             <% total_volume = 0 %>
            <% order.ordered_items.each do |ordered_item| %>
              <% total_volume += ordered_item.volume %>
            <% end %>
            <%= total_volume %>
          </td>
          <td>
            <%= order.status_i18n %>
          </td>
        </tr>
      <% end %>
    </table>
   <%= paginate @orders %>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-1">
    </div>
    <div class="col-xs-12">

    <h3 class="order-title-show">
      <strong>注文詳細画面</strong>
    </h3>
<!-- 注文詳細 -->
        <table class="table table-striped">
           <tr>
              <th>購入者</th>
              <td>
              <%= @order.customer.full_name %>
              </td>
           </tr>
            <tr>
              <th>配送先</th>
              <td>
                    <p>
                    〒<%= @order.postal_code %><%= @order.address %><br>
                    <%= @order.name %>
                    </p>
              </td>
            </tr>
           <tr>
              <th>支払い方法</th>
              <td><%= @order.payment_method_i18n %></td>
            </tr>
            <tr>
              <th>注文ステータス</th>
              <td>
                <%= form_with model: @order, url: admin_order_path(@order), method: :patch , local: true do |f| %>
                  <%= f.select :status,["入金待ち","入金確認","製作中","発送準備中","発送済み"], class: "ml-4" %>
                  <%= f.submit "変更", class: "btn btn-info" %>
                <% end %>
              </td>
            </tr>
          </table>

        <table class="table table-hover table-bordered">
           <thead>
             <tr class="info">
               <th>商品名</th>
               <th>単価(税込)</th>
               <th>数量</th>
               <th>小計</th>
               <th>製作ステータス</th>
             </tr>
           </thead>
           <tbody>
             <% total_fee = 0 #全商品の合計金額%>
             <% @ordered_items.each do | ordered_item | %>
               <tr>
                 <td>
                   <%= ordered_item.item.name %>
                 </td>
                 <td>
                   ¥<%= ordered_item.tax_in_price %>
                 </td>
                 <td>
                    <%= ordered_item.volume %>
                 </td>
                 <td>
                   <% sum = ordered_item.tax_in_price.floor * ordered_item.volume %>
                   ¥<%= sum.to_s(:delimited) %>
                 </td>
                 <td>
                  <%= form_with model: ordered_item, url: admin_ordered_item_path(ordered_item), method: :patch, local: true do |f| %>
                    <%= f.select :making_status, ["着手不可","製作待ち","製作中","製作完了"],:selected=> ordered_item.making_status, class: "ml-4" %>
                    <%= f.submit "変更", class: "btn btn-info" %>
                  <% end %>
                 </td>
               </tr>
               <% total_fee += sum %>
             <% end %>
           </tbody>
        </table>
      
        <table class='table'>
          <thead>
            <tr>
              <td>商品合計</td>
              <td>
                <%= total_fee %>円
              </td>
            </tr>
            <tr>
              <td>送料</td>
              <td>800円</td>
            </tr>
            <tr>
              <td>請求金額合計</td>
              <td> <%= total_fee + 800 %>円</td>
            </tr>
          </thead>
        </table>
    </
  </div>
</div>